crosswords/blog/urls.py
from django.urls import path

from blog import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("", views.PostListView.as_view(), name="post_list"),
    path("<slug>/", views.PostDetailView.as_view(), name="post_detail"),
]

crosswords/clues/models.py
from typing import Any

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVector, SearchVectorField
from django.db import models
from django.db.models import F
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from taggit.managers import TaggableManager

from core.models import BaseModel


class Publisher(BaseModel):
    name = models.CharField(_("name"), max_length=128, null=False, blank=False)
    slug = models.SlugField(
        _("slug"),
        max_length=128,
        unique=True,
        blank=True,
        editable=False,
    )
    source_url = models.CharField(
        _("source url"),
        null=True,
        blank=True,
        max_length=255,
    )
    is_active = models.BooleanField(_("is active"), default=True)
    pub_days = models.IntegerField(_("publication days"), default=0)
    publish_in_advance = models.SmallIntegerField(_("publish in advance"), default=0)
    listing_order = models.IntegerField(_("listing order"), default=0)

    tags = TaggableManager()

    class Meta:
        db_table = "publishers"
        verbose_name = _("publisher")
        verbose_name_plural = _("publishers")
        get_latest_by = ("created", "modified")

    def __str__(self) -> str:
        return self.name

    def save(self, *args: Any, **kwargs: Any) -> None:
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        return reverse("clues:publisher_detail", kwargs={"slug": self.slug})


class Crossword(BaseModel):
    pubdt = models.DateField(_("publication date"))
    source = models.URLField(_("source"), max_length=255, null=True, blank=True)
    publisher = models.ForeignKey(
        Publisher,
        verbose_name=_("publisher"),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="crosswords",
    )
    is_published = models.BooleanField(_("is published?"), default=False)

    tags = TaggableManager()

    class Meta:
        db_table = "crosswords"
        verbose_name = _("crossword")
        verbose_name_plural = _("crosswords")
        get_latest_by = ("created", "modified")

    def __str__(self):
        return f"{self.publisher.name} on {self.pubdt}"  # type: ignore

    def get_absolute_url(self):
        return reverse("clues:publisher_detail", kwargs={"pk": self.pk})


class Clue(BaseModel):
    ACROSS = "a"
    DOWN = "d"
    DIRECTION_CHOICES = [
        (ACROSS, _("Across")),
        (DOWN, _("Down")),
    ]

    clue = models.CharField(_("clue"), max_length=512)
    slug = models.SlugField(_("slug"), max_length=255, blank=True, db_index=True)
    answer = models.CharField(_("answer"), max_length=32)
    picture = models.ImageField(_("picture"), null=True, blank=True, upload_to="clues/")
    num = models.PositiveSmallIntegerField(_("number"), null=True, blank=True)
    direction = models.CharField(
        _("direction"),
        max_length=1,
        null=True,
        blank=True,
        choices=DIRECTION_CHOICES,
    )
    crossword = models.ForeignKey(
        Crossword,
        verbose_name=_("crossword"),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="clues",
    )
    description = SearchVectorField(_("description"), null=True)

    tags = TaggableManager()

    class Meta:
        db_table = "clues"
        verbose_name = _("clue")
        verbose_name_plural = _("clues")
        get_latest_by = ("created", "modified")
        indexes = (GinIndex(fields=("description",)),)

    def __str__(self) -> str:
        return self.clue

    def save(self, *args: Any, **kwargs: Any) -> None:
        if not self.slug:
            self.slug = slugify(self.clue)
        self.description = SearchVector(F("clue"), weight="A") + SearchVector(
            F("answer"), weight="B"
        )
        return super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        return reverse("clues:clue_detail", kwargs={"slug": self.slug})

crosswords/templates/base.html
{% load static %}<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Crosswords{% endblock title %}</title>
    {% block styles %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/Wruczek/Bootstrap-Cookie-Alert@gh-pages/cookiealert.css">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    {% endblock styles %}
    {% block extrastyles %}{% endblock extrastyles %}
  </head>
  <body class="d-flex flex-column h-100">
    <header>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
            <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'pages:home' %}">Crosswords</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'pages:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'clues:daily_crosswords' %}">Daily Crosswords</a>
                    </li>
                    <li class="nav-item dropdown dropdown-fullwidth">
                        <a class="nav-link dropdown-toggle"
                            href="{% url 'clues:publisher_list' %}"
                            id="cw-menu-publishers"
                            data-bs-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false"
                        >
                            Publishers
                        </a>
                        <div class="dropdown-menu" aria-labelledby="cw-menu-publishers">
                            <div class="container">
                                <div class="row flex-fill">
                                    <div class="col-sm-6 col-lg-3">
                                        first
                                    </div>
                                    <div class="col-sm-6 col-lg-3">
                                        second
                                    </div>
                                    <div class="col-sm-6 col-lg-3">
                                        third
                                    </div>
                                    <div class="col-sm-6 col-lg-3">fourth</div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:about' %}">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:contact_us' %}">Contact Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:privacy_policy' %}">Privacy Policy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
                    </li>
                </ul>
            </div>
            </div>
        </nav>
    </header>
    <main class="flex-shrink-0">
        <div class="container">
        {% block content %}{% endblock content %}
        </div>
    </main>
    <footer class="footer mt-auto py-3 bg-light">
        <div class="container text-center">
          <span class="text-muted">Copyright &copy; 2021 GSC</span>
        </div>
    </footer>
    <div class="alert text-center cookiealert" role="alert">
        <b>Do you like cookies?</b> &#x1F36A; We use cookies to ensure you get the best experience on our website. <a href="{% url 'pages:privacy_policy' %}" target="_blank">Learn more</a>
        <button type="button" class="btn btn-primary btn-sm acceptcookies">
            I agree
        </button>
    </div>
    {% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/Wruczek/Bootstrap-Cookie-Alert@gh-pages/cookiealert.js"></script>
    {% endblock scripts %}
    {% block extrascripts %}{% endblock extrascripts %}
  </body>
</html>